---
# file: ufw.yml
- name: ufw | Install ufw
  sudo: yes
  apt: pkg=ufw state=installed

- name: ufw | allow openssh
  sudo: yes
  ufw: rule=allow name=OpenSSH

- name: ufw | enabled ufw on startup with deny policy
  sudo: yes
  ufw: state=enabled policy=deny