---
- name: updates | set update cache and safe updates
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600 upgrade=safe

- name: updates | install common packages
  sudo: yes
  apt:
     pkg: "{{ item }}"
     state: present
     update-cache: yes
  with_items:
     - unattended-upgrades


- name: updates | activate unattended upgrades
  sudo: yes
  template:
    src: updates/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  notify: restart unattended upgrades
