---
- name: set update cache and safe updates
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600 upgrade=safe

- name: Install Common Packages
  sudo: yes
  apt: >
     pkg={{ item }}
     state=present
     update-cache=yes
  with_items:
     - unattended-upgrades

- name: set debconf defaults for unattended-upgrades
  sudo: yes
  shell: 'echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | debconf-set-selections'

- name: unattended-upgrades
  sudo: yes
  shell: 'dpkg-reconfigure -p critical unattended-upgrades'
