---
# handlers file for role-first_five_minutes/

# until service restart bug is fixed we fire command

- name: restart sshd
  sudo: yes
  command: service ssh restart

- name: restart unattended upgrades
  sudo: yes
  command: service unattended-upgrades restart

- name: update timezone
  sudo: yes
  command: dpkg-reconfigure --frontend noninteractive tzdata
